[package]
name = "evtx"
description = "Python bindings for https://github.com/omerbenamram/evtx"
version = "0.6.10"
authors = ["Omer Ben-Amram <omerbenamram@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"

[lib]
crate-type = ["cdylib"]

[dependencies]
evtx = {version = "0.6.6", default-features=false, features=["multithreading"]}
encoding = "0.2.33"
pyo3 = {version = "0.11.1", features=["extension-module"]}
pyo3-file = "0.3.2"
