[package]
name = "evtx"
version = "0.2.5"
authors = ["Omer Ben-Amram <omerbenamram@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
evtx = "0.2.5"
pyo3 = "0.6.0"
failure = "0.1.5"