[package]
name = "evtx"
version = "0.2.7"
authors = ["Omer Ben-Amram <omerbenamram@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
evtx = "0.2.5"
pyo3 = {version = "0.6.0", features = ["extension-module"]}
failure = "0.1.5"