[package]
name = "evtx"
version = "0.6.6"
authors = ["Omer Ben-Amram <omerbenamram@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
evtx = {version = "0.6.6", default-features=false, features=["multithreading"]}
encoding = "0.2.33"
pyo3 = "0.11.0"
pyo3-file = "0.3.2"
